### ISSUE TITLE
Bug: Home Assistant 2023.1.0b4: TypeError: AreaEntry.__init__() missing 1 required positional argument: 'aliases'

### ISSUE THREAD

**Issue by ovitters** [jseidl/hass-magic_areas#265]
**Describe the bug**
The magic_areas integration doesn't start/work with 2023.1 beta releases. I get a notification in the 'Notifications' section of HA.

**To Reproduce**
1. Go to Settings → Config → Updates
2. Click on '....' (top right of the screen)
3. Enable beta channel
4. Then update to current 2023.1.0 beta release
5. Obviously, magic_areas should've been enabled via hacs

**Expected behavior**

It to start up without an error in the logs.

**Screenshots**

As text:
```
Logger: homeassistant.setup
Source: custom_components/magic_areas/__init__.py:67
Integration: magic_areas ([documentation](https://github.com/jseidl/hass-magic_areas/wiki), [issues](https://github.com/jseidl/hass-magic_areas/issues))
First occurred: 12:01:24 (1 occurrences)
Last logged: 12:01:24
Error during setup of component magic_areas

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/magic_areas/__init__.py", line 67, in async_setup
    AreaEntry(
TypeError: AreaEntry.__init__() missing 1 required positional argument: 'aliases'
```

As image:
![image](https://user-images.githubusercontent.com/673889/210248816-679abe32-6455-4315-bcf7-de18d7a74204.png)

**Additional context**

https://developers.home-assistant.io/blog/ (didn't notice an announcement but should be here I assume)
https://rc.home-assistant.io/blog/2022/12/28/release-20231/#aliases-for-voice-assistants (it mentions something about aliases, but just the user side of it)

**Comment by pascalmtts** [comment]
When will this be fixed? I updated my HA today and now my whole lights are not working anymore 🙈

**Comment by johnjoemorgan** [comment]
> When will this be fixed? I updated my HA today and now my whole lights are not working anymore 🙈

See issue #270 for temporary fix

**Comment by jseidl** [comment]
Resolved on latest release, please update
