### ISSUE TITLE
Magic Areas 3.0.0 - Beta - Issue Tracker

### ISSUE THREAD

**Issue by jseidl** [jseidl/hass-magic_areas#144]
This is an issue thread to track bugs within the `3.0.0` release. 

> Please **NO FEATURE REQUESTS HERE, ONLY BUGS**. Please cut a fresh ticket for feature requests

```
THIS IS A BREAKING RELEASE, READ THE WIKI FOR INFORMATION ON CONCEPTS AND CONFIGURATION!
```

Release download: https://github.com/jseidl/hass-magic_areas/releases/tag/3.0.0-beta
Wiki/Documentation: https://github.com/jseidl/hass-magic_areas/wiki

**Comment by cerebrate** [comment]
Count me in, certainly! I love a good beta.

(Also, for anyone else doing this who doesn't already know, `.storage/core.config_entries` is the file you want to copy your existing configuration out of if it's complex and clicking around taking notes lacks appeal. 😄 )

**Comment by cerebrate** [comment]
Got one, and it's quite the issue:

I use light groups principally to create the groiups, and not to control the lights. (Reasons: I have adaptive_lighting set up for most of my room lights, and my presence detection isn't yet reliable enough; once the latter changes, I'm going to start using it more fully, but that is not this day.)

So, for example, if I copy my bathroom config, it looks like this:

```
              {
                  "entry_id": "8555194b441ace28b1dc3c524aeb071e",
                  "version": 1,
                  "domain": "magic_areas",
                  "title": "Bathroom",
                  "data": {
                      "on_states": [
                          "on",
                          "home",
                          "playing",
                          "open"
                      ],
                      "sleep_lights": [],
                      "presence_sensor_device_class": [
                          "motion",
                          "occupancy",
                          "presence"
                      ],
                      "update_interval": 60,
                      "notification_devices": [],
                      "aggregates_min_entities": 2,
                      "exclude_entities": [],
                      "clear_timeout": 60,
                      "notify_on_sleep": false,
                      "main_lights": [],
                      "include_entities": [],
                      "type": "interior",
                      "sleep_state": "on",
                      "features": [],
                      "icon": "mdi:texture-box",
                      "night_state": "on",
                      "sleep_timeout": 0,
                      "name": "Bathroom",
                      "id": "bathroom"
                  },
                  "options": {
                      "type": "interior",
                      "include_entities": [],
                      "exclude_entities": [],
                      "presence_device_platforms": [
                          "media_player",
                          "binary_sensor"
                      ],
                      "presence_sensor_device_class": [
                          "motion",
                          "occupancy",
                          "presence"
                      ],
                      "on_states": [
                          "on",
                          "home",
                          "playing",
                          "open"
                      ],
                      "clear_timeout": 60,
                      "update_interval": 60,
                      "icon": "mdi:toilet",
                      "features": {
                          "media_player_groups": {},
                          "health": {},
                          "area_aware_media_player": {
                              "notification_devices": [],
                              "notification_states": [
                                  "extended",
                                  "occupied"
                              ]
                          },
                          "aggregates": {
                              "aggregates_min_entities": 1
                          },
                          "presence_hold": {
                              "presence_hold_timeout": 0
                          },
                          "light_groups": {
                              "overhead_lights": [
                                  "light.bathroom_light_center",
                                  "light.bathroom_light_left",
                                  "light.bathroom_light_right"
                              ],
                              "overhead_lights_states": [],
                              "overhead_lights_act_on": [],
                              "sleep_lights": [],
                              "sleep_lights_states": [],
                              "sleep_lights_act_on": [],
                              "accent_lights": [],
                              "accent_lights_states": [],
                              "accent_lights_act_on": [],
                              "task_lights": [],
                              "task_lights_states": [],
                              "task_lights_act_on": []
                          }
                      },
                      "secondary_states": {
                          "accent_entity": "",
                          "accent_state": "on",
                          "extended_time": 120,
                          "extended_timeout": 300,
                          "sleep_timeout": 60,
                          "sleep_state": "off",
                          "sleep_entity": "input_boolean.day_mode",
                          "dark_state": "on",
                          "dark_entity": ""
                      }
                  },
                  "pref_disable_new_entities": false,
                  "pref_disable_polling": false,
                  "source": "user",
                  "unique_id": "Bathroom",
                  "disabled_by": null
              },
```

...in which as you can see, I'm using none of the options to control the lights and so - I would think - nothing of the sort would happen.

Except I can't get the lights in there to turn _off_ . If I turn them off, they come back on in a matter of seconds. The same goes for another area, and I also have one, with similar all-disabled light control options, in which the lights turn off occasionally by themselves for no readily explicable reason.

**Comment by jseidl** [comment]
This is very weird. Will replicate this setup in by testbed and try to replicate. Thanks for reporting!

**Comment by jseidl** [comment]
I think I've found the culprit. Definitely is the global area light group ("$area_lights").

Normal secondary groups have the following snippet which would prevent that

```
        # Do not handle lights that are not tied to a state
        if not self.assigned_states:
            _LOGGER.debug(f"{self.name}: No assigned states. Noop.")
            return False
```

But the global area light group doesn't. Will fix this in the next mins.

**Comment by jseidl** [comment]
Can you try changing line 194 on `light.py` from

```
# If we don't, just turn on all of them
return self._turn_on()
```

to 

```
if AREA_STATE_OCCUPIED in new_states:
        # If we don't, just turn on all of them
        return self._turn_on()
```

**Comment by cerebrate** [comment]
Also, I note that when picking states for lights to be on in, I can only see _occupied_, _extended_, and _sleep_, not the _accented_ or _dark_ secondary states mentioned on the wiki?

**Comment by cerebrate** [comment]
Okay, the lights-turning-off one is still happening, but I have a better profile of it now. 

It looks as though even without any configuration (as per file above, in that respect; this is happening in every room with a presence sensor) to tell magic_areas to operate the lights according to occupancy, it still _is_ doing so. The lights go out when presence is first detected (at which point they're already on, so no change) and then clears, at which point they go off.

Should presence again be detected, the lights do turn on again.

Also, interestingly, this is affecting _all_ lights in the area, not just those mentioned in the configuration; in my office, this switches off and on the LED strip I use for my 3D printer, which while in the "Office" area in Home Assistant, isn't included as a light in the light_groups configuration for magic_areas. (And, indeed, isn't part of the light.office_lights or light.overhead_lights_office entities it creates.)

**Comment by jseidl** [comment]
> Also, I note that when picking states for lights to be on in, I can only see _occupied_, _extended_, and _sleep_, not the _accented_ or _dark_ secondary states mentioned on the wiki?

 Yeah that's true, `dark` shouldn't be there, will fix the documentation as dark is a required state apart from others, although `accented` should show. Will check.

> It looks as though even without any configuration (as per file above, in that respect; this is happening in every room with a presence sensor) to tell magic_areas to operate the lights according to occupancy, it still is doing so. The lights go out when presence is first detected (at which point they're already on, so no change) and then clears, at which point they go off.

This is actually the default behavior if you don't specify any lights (it treats all of them instead). That might be the wrong way to default but it's just how it was coded in the first place. Will give some thought. If you don't want any control unfortunately you have to give up light groups functionality which is not ideal.

> Also, interestingly, this is affecting all lights in the area
Yes, this is the same as above. Will work on solving that. Having a "default all" really forces you to use the control functionality. I guess I never ran into that because whenever I don't want the lights to turn on I "trick it" into thinking it's always bright with a mock sensor, but you have a good point.

**Comment by jseidl** [comment]
> Trying to configure my rooms after deleting most of them to reset, I get this https://drive.google.com/file/d/1yZ07SxhHledwpHuxDea-qwLaqH2m8PQz/view?usp=sharing
> 
> Not sure what the flow is referring to.

This is weird, can you try deleting the offending area and restarting again? Also reload your integrations page before trying to configure again

**Comment by jseidl** [comment]
Yeap, I'm also considering this. No worries I'll take a stab at it tonight. I'm thinking on adding a `turn_on_state` to the `all` group and a drop down between ("","occupied") which would do the same thing. If you select occupied you have control, if empty, no control. This would allow to grow to other states in the future (but it probably wont). Still churning which would be the better way to go around this. Thanks for the report!

**Comment by jseidl** [comment]
> [I also took a whack at the most naive solution, adding a boolean option to light groups that defaults to True, with the notion that it would simply no-op state_change_primary and state_change_secondary if toggled off, but I wasn't able to figure out enough about HA/Voluptuous validation in the time I've had spare to make that work.]

I ended up going that route. Simpler. Check out the release branch, update has been tested on both test env and my prod env (house), works well but now you have to go back and reconfigure all areas because the default is `False`

**Comment by jseidl** [comment]
> I see for the Dark detector entity, you are expecting state which excludes light sensors until you create a binary sensor for it, correct?

The `dark entity ` whenever in `dark state` will add `dark` the area's secondary state. I just updated the wiki with some better explanation about `dark`: https://github.com/jseidl/hass-magic_areas/wiki/Light-Groups

I have a `illuminance` sensor (`weatherstation_illuminance`) outside and then a template binary sensor (`weatherstation_light`) which is `on` when `illuminance` is greater than `200` (YMMV) and `off` otherwise. Then I use this template sensor as my dark entity with dark state of `off` (meaning whenever this entity is off, then it's `dark`). Hope I've managed to explain it right

**Comment by jseidl** [comment]
> Clear timeout... Is not in seconds right?
Everything is in seconds BUT clear timeout changes once it enters the extended state (configurable).

Also check the State wiki https://github.com/jseidl/hass-magic_areas/wiki/Area-State

So whenever any of your presence sensors goes on, it sets the area to occupied (if not already) and it keeps there until `clear_timeout`. If any sensor triggers during that timeout wait, it resets the timeout again. The room will only go out of occupied state if there are no triggers from the presence sensor in `clear_timeout` seconds

**Comment by caphm** [comment]
@jseidl Sorry I haven't been able to contribute to this during the past months. I'm afraid I won't be able to in the foreseeable future, either, since me and my wife had a kid and I'm pretty swamped with work.

**Comment by jseidl** [comment]
> @jseidl Sorry I haven't been able to contribute to this during the past months. I'm afraid I won't be able to in the foreseeable future, either, since me and my wife had a kid and I'm pretty swamped with work.

Brother, no need to apologize, your contributions surely rewrote the story of Magic Areas and I will forever owe you a beer for that. I'll pick up from here! Hope you can still use and report feature requests / bug reports whenever you have a break!

Congrats on the baby!

**Comment by andyinno** [comment]
Hi!

I just upgraded to the last code published.
after the update the lights do not change their state anymore.

I reconfigured everything from zero but as the wiki states automatic light control needs to be checked in the configuration, I do not have this setting anymore.

Is the wiki still up to date or there is some difference here?

Thank you in advance

**Comment by jseidl** [comment]
Hey @andyinno, I've recently switched from the configuration "automatic light control" into making into a switch so you can switch light control on and off anytime. Look for a switch called "light control ($area)" and turn it on

**Comment by andyinno** [comment]
Yup, the switch is created.
Toggling the switch to on, lights are turned on and off.

Thank you!

**Comment by Bodge-IT** [comment]
Cool feature!

**Comment by andyinno** [comment]
Yes, cool feature.

I think more options, more personalization, means more possibilities and adapt to every user use cases

**Comment by jseidl** [comment]
Yeah I have guests sleeping in the family room/living room and trying to manipulate presence hold to keep the lights off was a pain. That shall solve it!

Furthermore folks, I've created a Discord server so we can have a tighter comms channel for the MA community, here's the link https://discord.gg/8vxJpJ2vP4

**Comment by klatka** [comment]
Using the beta I noticed a bug in attributes of created light groups.
Instead of covers there should be a list of lights.

Example: `light.lounge_lights`
```
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
  - xy
color_mode: color_temp
brightness: 128
color_temp: 397
hs_color:
  - 28.827
  - 71.874
rgb_color:
  - 255
  - 159
  - 71
xy_color:
  - 0.546
  - 0.389
covers:
  - cover.level_schlafzimmer
  - cover.level_wohnbereich
  - cover.level_buro
  - cover.level_lounge
icon: mdi:lightbulb-group
friendly_name: Licht in der Lounge
supported_features: 40
```

**Comment by klatka** [comment]
I have another issue:
I configured a light as a sleep light in Area A. 
Then I remove this light from this area A I cannot reconfigure area A because it is not listed anymore in settings, so I cannot uncheck this light. But I cannot save my configuration either because this light is still mapped and in consequence, I get a mapping error.
Lights that do not exist in the Area should be automatically get removed from the configuration in this step.

**Comment by mouth4war** [comment]
Climate groups should also consider sleep state in addition to occupied and extended.

**Comment by mouth4war** [comment]
Is the climate group supposed to work with sleep state also? It feels like a bug to me. It should work for extended/occupied and sleep.

Maybe config flow step should be similar to light groups with each climate (and hopefully fan) entity listed and then check boxes for each state .

**Comment by mszoernyi** [comment]
I replaced my automations with magic areas and struggle to get my LCN integrated lights to show up in the config dialogs. It works with my Zigbee lights, they show up normally when configuring an area with light groups.

This is how the dialog looks like for LCN integrated light
![image](https://user-images.githubusercontent.com/668269/161375511-91b415b0-b2cf-4c33-9437-5f84a9a9c496.png)

And here with Zigbee lights in a different area
![image](https://user-images.githubusercontent.com/668269/161375578-e0fa5dea-9989-4c6b-b505-de24be0c8696.png)

I wonder if this is an issue in the LCN integration not setting some attributes properly. I can control all lights normally in HA and they worked with my own automations before.

**Comment by andyinno** [comment]
Is this happening also if you manually add the devices to the area?

In the first tab of the configuration wizard.are the light in the area right?

**Comment by mszoernyi** [comment]
This is the first dialog of the configuration flow
![image](https://user-images.githubusercontent.com/668269/161377365-d957a753-6c8a-4ec1-8f4e-1a3ac65f74fa.png)

I can see the lights in the `Include entities for this area` dropdown 
![image](https://user-images.githubusercontent.com/668269/161377423-a60fd197-e2f2-48c1-888b-fa58c1b4b3af.png)

but even if I select them here they don't show up in the following dialogs.

**Comment by jseidl** [comment]
Hey @mszoernyi can you post a screenshot of both entities on the `Developer Tools` screen? This will show the extended attributes and help figure out what is going on there.

Also, in HA are those lights assigned to that area already? Do the area assignment holds on home assistant's area?

**Comment by Bodge-IT** [comment]
Hi @jseidl the HA April beta (b1 through b6) throwing error on 'Area aware media player' option.
`Unable to prepare setup for platform magic_areas.media_player: Platform not found (cannot import name 'MediaGroup' from 'homeassistant.components.group.media_player' (/usr/src/homeassistant/homeassistant/components/group/media_player.py)).`

Something to do with new Group config through UI?

**Comment by mszoernyi** [comment]
> Hey @mszoernyi can you post a screenshot of both entities on the `Developer Tools` screen? This will show the extended attributes and help figure out what is going on there.
> 
> Also, in HA are those lights assigned to that area already? Do the area assignment holds on home assistant's area?

@jseidl 
![image](https://user-images.githubusercontent.com/668269/162384253-b590015b-e789-4a6d-8613-2ee2e460de70.png)

**Comment by felix63** [comment]
plenty of problems still running beta 2.0 after updating to 2022.4

Having to find work-arounds, but that is the price for working with HACS/beta

**Comment by Bodge-IT** [comment]
@felix63  Thanks for the update.  Maybe you could elaborate?  This would save @jseidl from having to read your mind.

**Comment by felix63** [comment]
Already shared on Discord, but get a lot of errors all over the place. See my logfile. Have problems with manually adjusted light groups, binaries and such...

[homeassistant.log](https://github.com/jseidl/hass-magic_areas/files/8458695/homeassistant.log)
.

**Comment by mouth4war** [comment]
Climate group should stay on when sleep mode is on but it is being turned off when extended is cleared

**Comment by jseidl** [comment]
> Already shared on Discord, but get a lot of errors all over the place. See my logfile. Have problems with manually adjusted light groups, binaries and such...
> 
> [homeassistant.log](https://github.com/jseidl/hass-magic_areas/files/8458695/homeassistant.log) .

@felix63 please check the latest update on the branch we've been working on, lemme know if that works

**Comment by jseidl** [comment]
> Climate group should stay on when sleep mode is on but it is being turned off when extended is cleared

Can you elaborate? Extended shouldn't be cleared until the area itself is clear

**Comment by scoobee81** [comment]
Is anyone having issues with Sleep Mode? I've tried deleting, re-adding to areas, reloading, different configurations.

I have two lights in the Area `Ground Floor Hallway`

No matter which way i configure it, both lights will turn on. What I am looking for, is that when `input_boolean.hallway_auto_light_control_sleep` is `true` then only turn on the small lamp when there is motion.

What's the best way to share my config other than Screenclips? Is each area stored in a Text File Somewhere?

**Comment by jseidl** [comment]
Hi! So either there's something funny with your config or you found a bug! Yay!

If it's a config issue, I think I can narrow down the problem with 2 screenshots (hopefully!) Send me screenshots of the "Secondary states" and "Light Group" configuration.

You're looking for something like this:
![image](https://user-images.githubusercontent.com/283041/166857834-f4348849-e372-458f-b242-cf5936d0bde4.png)

And on light groups, you have "Overhead", "Accent", "Task" and "Sleep". The confusing part is that all of those groups have no automation at all at first, they're just groups and will create the `light.area_$group_name_lights` light group on HA.

In order for the lights to be assigned to a given state (say, sleep), you have to go to the group of lights you wanna react to that state, and then select that state from "States which $group_name lights are turned on". In that screenshot, you can see that I have my Overhead lights assigned to the states "extended", "occupied" and "sleep".

There's a note there, if you don't want a given light to turn OFF when on sleep mode, be sure to assign them to the "sleep" state as well. You can chose if you want them to be switched only when the area occupancy changes or anytime the area changes the given state. This is useful if you wanna just the night lights to turn on if you walk into the room but not if you're already there with your main lights on.

I might rename the "Sleep Lights" group to "Night lights" or something like that to avoid this confusion in the future.

**Comment by danielbrunt57** [comment]
"I might rename the "Sleep Lights" group to "Night lights" or something like that" - how about Subdued or Romantic??

**Comment by scoobee81** [comment]
![image](https://user-images.githubusercontent.com/51600820/166885068-aa04088b-4b14-419c-a2ed-4f751209f24a.png)

![image](https://user-images.githubusercontent.com/51600820/166885093-915178a1-2b1d-4a40-8018-d35e96830a3c.png)

**Comment by felix63** [comment]
Still have issues with areas with multiple motion sensors...
`2022-05-05 18:18:03 ERROR (MainThread) [custom_components.magic_areas.base] [Area (Living room)] Error getting entity state for '['binary_sensor.living_room_pir_occupancy', 'binary_sensor.display_pir_occupancy']': 'list' object has no attribute 'lower'
2022-05-05 18:18:03 ERROR (SyncWorker_6) [root] Uncaught exception
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
2022-05-05 18:18:04 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform magic_areas
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/magic_areas/binary_sensor.py", line 266, in async_added_to_hass
await self._initialize()
File "/config/custom_components/magic_areas/binary_sensor.py", line 294, in _initialize
await self._setup_listeners()
File "/config/custom_components/magic_areas/binary_sensor.py", line 307, in _setup_listeners
async_track_state_change(self.hass, self.sensors, self.sensor_state_change)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in async_track_state_change
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in <genexpr>
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
AttributeError: 'list' object has no attribute 'lower'
2022-05-05 18:18:04 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform magic_areas
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/magic_areas/base.py", line 291, in async_added_to_hass
await self._initialize()
File "/config/custom_components/magic_areas/binary_sensor.py", line 599, in _initialize
await self._setup_listeners()
File "/config/custom_components/magic_areas/base.py", line 307, in _setup_listeners
async_track_state_change(self.hass, self.sensors, self.sensor_state_change)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in async_track_state_change
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in <genexpr>
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
AttributeError: 'list' object has no attribute 'lower'
2022-05-05 18:18:04 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up magic_areas platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/magic_areas/binary_sensor.py", line 266, in async_added_to_hass
await self._initialize()
File "/config/custom_components/magic_areas/binary_sensor.py", line 294, in _initialize
await self._setup_listeners()
File "/config/custom_components/magic_areas/binary_sensor.py", line 307, in _setup_listeners
async_track_state_change(self.hass, self.sensors, self.sensor_state_change)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in async_track_state_change
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 172, in <genexpr>
entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)
AttributeError: 'list' object has no attribute 'lower'`
<img width="231" alt="Schermafbeelding 2022-05-05 om 18 17 02" src="https://user-images.githubusercontent.com/16501940/166968196-8da0695b-82e8-471e-8d31-3da3bcef7a33.png">
<img width="312" alt="Schermafbeelding 2022-05-05 om 18 12 25" src="https://user-images.githubusercontent.com/16501940/166968200-49ab0851-f68e-4398-ad3e-2ebb605fe2fe.png">
<img width="312" alt="Schermafbeelding 2022-05-05 om 18 12 16" src="https://user-images.githubusercontent.com/16501940/166968202-99058e7a-4a97-4a4c-bae1-2935e47508d7.png">
<img width="312" alt="Schermafbeelding 2022-05-05 om 18 12 00" src="https://user-images.githubusercontent.com/16501940/166968206-9d5ffbc3-76de-48e5-baa7-97bb3cb09c46.png">
<img width="312" alt="Schermafbeelding 2022-05-05 om 18 11 44" src="https://user-images.githubusercontent.com/16501940/166968209-b924fa95-a706-4cd7-8202-805c53ffe5f1.png">
<img width="231" alt="Schermafbeelding 2022-05-05 om 18 11 08" src="https://user-images.githubusercontent.com/16501940/166968213-6e9f2554-ad3e-4ce3-9ab4-95d075ee5a4f.png">

**Comment by hirsts** [comment]
I have an issue with Light Groups and light entities not showing up in the dialogue. 

Light Groups: 
If I don't select "Create Light Groups" I then don't get the option to configure specific light entities. If I do select "Create Light Group", MA then creates light groups with the same name and entity name as an existing light. For example in my office I have two lights, the main ceiling lights created as "Office Lights <light.office_lights>" and the lamp created as "Office Lamp<light.office_lamp_on_off>". MA then creates a light group called "Office Lights<light.office_lights_2>". When the area is triggered MA turns on "Office Lights<light.office_lights_2>" which turns on both the main ceiling lights and the lamp.

Light Entities not being displayed:
This issue is perhaps the main issue. If light entities were being detected I would have no need to select "Create Light Groups" and therefore avoid the confusion above.

![image](https://user-images.githubusercontent.com/3762005/177234556-99e54bc3-babb-4300-a31b-dcd716988cd4.png)

**Comment by jseidl** [comment]
> If I don't select "Create Light Groups" I then don't get the option to configure specific light entities.

That's expected. You can only configure `Light Group` options if you select it. 

>  If I do select "Create Light Group", MA then creates light groups with the same name and entity name as an existing light.

Not quite, you just happen to have the light named the same way Light Group names them. Light group will create a group called "$area_name Lights" with all the lights in that area. If you have them named "Office lights" then MA will conflict with it. Try renaming to "office celing lights" and you'll get the group created correctly.

In the Light Groups configuration you'll be able to place your light into 4 distinct groups:
* Overhead lights
* Sleep lights
* Accent lights
* Task lights

These groups are just names, they don't have any specific behavior tied to their naming. The behavior when they turn on or off is given for the states you tie the group to, for example if you set the Accent group to only come up in the `extended` state, and the Overhead lights to come up in both `occupied` and `extended`, when the area gets occupied, first the ceiling lights will come on, then the accent after some while (default 300 seconds). 

No light entities are created without the Light Group feature being enabled.

@hirsts lemme know if you have further questions. Feel free to hop on our [discord](https://discord.gg/8vxJpJ2vP4) as well.

**Comment by jseidl** [comment]
Hey folks, closing this as the release 3.0 is out and no longer in beta. If you still have issues please cut a new ticekt.
