### ISSUE TITLE
Light groups break in HA 2021.8.0+

### ISSUE THREAD

**Issue by cerebrate** [jseidl/hass-magic_areas#131]
After upgrading Home Assistant to 2021.8.0, I no longer see the light group entities created for those areas in which magic_areas is configured to create them. On investigating the logs, I see the following error repeated for each area:

```
Error while setting up magic_areas platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/magic_areas/light.py", line 45, in async_setup_entry
    async_add_entities([LightGroup(group_name, light_entities)])
TypeError: __init__() missing 1 required positional argument: 'entity_ids'
```

Breaking change?

**Comment by jseidl** [comment]
Breaking change indeed. Thanks for the fix!

**Comment by cerebrate** [comment]
No problem. Thanks for the integration - it saves me a ridiculous amount of time!
