### ISSUE TITLE
Bug: initialization error after upgrading to 3.0.2 in HA 2022.12

### ISSUE THREAD

**Issue by juacas** [jseidl/hass-magic_areas#282]
**Describe the bug**
After upgrading to 3.0.2 the component refused to start up with the error:

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.setup
Source: custom_components/magic_areas/__init__.py:67
Integration: Magic Areas (documentation, issues)
First occurred: 23:30:29 (1 occurrences)
Last logged: 23:30:29

Error during setup of component magic_areas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/magic_areas/__init__.py", line 67, in async_setup
    AreaEntry(
TypeError: AreaEntry.__init__() got an unexpected keyword argument 'aliases'

**To Reproduce**
- have home assistant 2022.12.8
- Upgrade to version 3.0.2
- Rename an existing area
- Restart HA.

**Comment by jseidl** [comment]
You need to update your homeassistant to the latest version. Unfortunately I forgot to update the minimum HA version on the latest release.

**Comment by jseidl** [comment]
Closing this one, please reopen if you still have issues.
