### PR TITLE
Update LightGroup signature.

### LINKED ISSUE #131: Light groups break in HA 2021.8.0+
After upgrading Home Assistant to 2021.8.0, I no longer see the light group entities created for those areas in which magic_areas is configured to create them. On investigating the logs, I see the following error repeated for each area:

```
Error while setting up magic_areas platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/magic_areas/light.py", line 45, in async_setup_entry
    async_add_entities([LightGroup(group_name, light_entities)])
TypeError: __init__() missing 1 required positional argument: 'entity_ids'
```

Breaking change?

### PR DESCRIPTION
**Pull request by cerebrate**
Patches the signature of the created LightGroup objects such that light groups can be successfully created under HA 2021.8.0 and above. (Fixes #131 .)

### CODE REVIEW

**Comment by jseidl** [comment]
Thanks a lot!
